// Generated by CoffeeScript 1.7.1
var unPlayedAssessment;

unPlayedAssessment = "8e5352e8-33d4-4085-ac05-c6314008164b";

QUnit.test("API Client Set Host", function(assert) {
  Traitify.setHost("hi");
  assert.equal(Traitify.host, "https://hi", "Setting Host Succeeds");
  Traitify.setHost("https://new_hi");
  assert.equal(Traitify.host, "https://new_hi", "Setting Host with https Succeeds");
  Traitify.setHost("http://new_hi_with_https");
  return assert.equal(Traitify.host, "https://new_hi_with_https", "Setting Host with http is changed for https Succeeds");
});

QUnit.test("API Client Set Version", function(assert) {
  Traitify.setVersion("v2");
  return assert.equal(Traitify.version, "v2", "Setting Version");
});

QUnit.test("API Client Set Public Key", function(assert) {
  Traitify.setPublicKey("here-is-the-key");
  return assert.equal(Traitify.publicKey, "here-is-the-key", "Setting public key Succeeds");
});

QUnit.asyncTest("API Client Get Slides", function(assert) {
  Traitify.setVersion("v1");
  Traitify.setHost("api-sandbox.traitify.com");
  Traitify.setPublicKey("gglvv58easpesg9ajbltavb3gr");
  return Traitify.getSlides(unPlayedAssessment, function(slides) {
    assert.equal(slides.length, 84, "Returns 84 slides");
    assert.equal(slides[0].caption, "Navigating", "Returns 84 slides");
    return QUnit.start();
  });
});

QUnit.asyncTest("API Client Get Decks", function(assert) {
  Traitify.setVersion("v1");
  Traitify.setHost("api-sandbox.traitify.com");
  Traitify.setPublicKey("gglvv58easpesg9ajbltavb3gr");
  return Traitify.getDecks(function(decks) {
    assert.equal(decks[0].name, "Career Deck", "Returns 84 slides");
    return QUnit.start();
  });
});
