// Generated by CoffeeScript 1.7.1
describe("API Endpoints", function() {
  return this.test("setHost", function() {
    Traitify.setHost("awesome").host;
    this.it(Traitify.setHost("awesome").host).should_be_equal_to("awesome");
    this.it(Traitify.setVersion("version").version).should_be_equal_to("version");
    return this.it(Traitify.setPublicKey("key").publicKey).should_be_equal_to("key");
  });
});
