// Generated by CoffeeScript 1.8.0
window.mocker = Object();

window.XMLHttpRequest = function() {
  this.open = function(method, url) {
    this.requestMethod = method;
    return this.requestUrl = url;
  };
  this.send = function(params) {
    var byMethodAndUrl, err;
    try {
      byMethodAndUrl = window.mocker.mocks[this.requestMethod][this.requestUrl];
      if (!params) {
        params = JSON.stringify(Object());
      }
      this.response = byMethodAndUrl[params];
      return this.onload();
    } catch (_error) {
      err = _error;
      return console.log("" + this.requestMethod + " with url " + this.requestUrl + " and " + params + " is not mocked");
    }
  };
  this.headers = Object();
  this.setRequestHeader = function(key, value) {
    return this.headers[key] = value;
  };
  this.withCredentials = function() {
    return Object();
  };
  return this;
};

window.XDomainRequest = window.XMLHttpRequest;

window.mocker.mocks = Object();

window.mocker.mock = function(method, url, params, data) {
  if (typeof window.mocker.mocks[method] === "undefined") {
    window.mocker.mocks[method] = Object();
  }
  if (typeof window.mocker.mocks[method][url] === "undefined") {
    window.mocker.mocks[method][url] = Object();
    return window.mocker.mocks[method][url][params] = JSON.stringify(data);
  }
};
